# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20170929_1353'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together=set([('customer', 'category', 'acquired_value', 'acquired_date')]),
        ),
    ]
